version: "3.3"
services:
    db:
        build:
            context: ./couchbase
        ports:
            - "8091:8091"
            - "8092:8092"
            - "8093:8093"
            - "8094:8094"
            - "11210:11210"
    node:
        build:
            context: ./node
        ports: 
            - "8888:8888"
        links:
            - db
        # environment:
        #     DATABASE_URL: http://localhost:8091
    nginx:
        build:
            context: ./nginx
        links: 
            - node
        ports:
            - "80:80"