version: "3.3"
services:
    db:
        image: arungupta/couchbase
        ports:
            - "8091:8091"
            - "8092:8092"
            - "8093:8093"
            - "8094:8094"
            - "11210:11210"
    node:
        image: node:latest
        ports: 
            - 8888:8888
        links:
            - "db:couchbase"
    nginx:
        image: nginx
        links: 
            - "node"
        ports:
            - "80:80"
